apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s
  labels:
    app: demo-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-k8s
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demo-k8s
          image: demo-k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
